# Generated by Django 3.0.8 on 2020-07-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userbio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
